spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao_client_id}
            client-secret: ${kakao_client_secret}
            redirect-uri: ${main_url}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - profile_nickname
              - account_email
            client-authentication-method: client_secret_post
            client-name: kakao
            provider: kakao
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}
            redirect-uri: ${main_url}/login/oauth2/code/google
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: google
            provider: google
          naver:
            client-id: ${naver_client_id}
            client-secret: ${naver_client_secret}
            redirect-uri: ${main_url}/login/oauth2/code/naver
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: naver
            provider: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response




jwt:
  secret-key: ${jwt_secret}
  expiration-time: 3600000
