spring.application.name: sparta-tigers
spring.profiles.active: local

spring:
  config:
    import:
      - db.yml
      - redis.yml

  # ?? ??? ?? ????
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100