spring.application.name: sparta-tigers
spring.profiles.active: local

spring:

  config:
    import:
      - db.yml
      - redis.yml
      - application-social.yml
      - application-s3.yml
  web:
    resources:
      add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

logging:
  level:
    com.sparta.sparta-tigers.global.config.StompAuthInterceptor: info # 개발할 때 info 운영 단계에서는 warn으로
    org.springframework.security: debug
    org.springframework.security.web: debug
    org.springframework.security.authentication: debug
    org.springframework.security.authorization: debug
    org.springframework.security.config: debug
    org.springframework.security.core: debug

