name: CI/CD to EC2

on:
  push:
    branches:
      - "main"
      - "dev"

env:
  ECS_CLUSTER: sparta-tigers-cluster
  ECS_SERVICE: sparta-tigers-task-service
  CONTAINER_NAME: sparta-tigers-container
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/sparta-tigers

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git SHA
        id: git-info
        run: echo "IMAGE_TAG=main-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-22.04

    needs: build

    if: github.ref == 'refs/heads/main' # main 브랜치만 배포

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Replace image URI and inject environment variables
        run: |
          IMAGE_URI=${IMAGE_NAME}:${IMAGE_TAG}
          export DB_URL=${{ secrets.DATABASE_LOCAL_URL_EC2 }}
          export DB_USER=${{ secrets.DATABASE_LOCAL_USERNAME }}
          export DB_PASSWORD=${{ secrets.DATABASE_LOCAL_PASSWORD }}

          sed "s|DOCKER_IMAGE_URI_REPLACE_ME|$IMAGE_URI|g" aws/ecs/task-definition.json > aws/ecs/task-definition-tmp.json

          envsubst '$DB_URL $DB_USER $DB_PASSWORD' < aws/ecs/task-definition-tmp.json > aws/ecs/task-definition-final.json

          echo "== FINAL TASK DEFINITION =="
          cat aws/ecs/task-definition-final.json

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: aws/ecs/task-definition-final.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
