name: CI

on:
  pull_request:
    branches:
      - "main"
      - "dev"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
